version: '3'
services:
    web:
      container_name: flask_profile_matcher
      image: flask_profile_matcher
      build:
          context: .
          dockerfile: ./infrastructure/Dockerfile
      environment: 
        PYTHONUNBUFFERED: 1
        WAIT_HOSTS: "dynamodb:8000,dynamodb_admin:8001"
        WAIT_HOSTS_TIMEOUT: 600
        WAIT_SLEEP_INTERVAL: 1
        WAIT_HOST_CONNECT_TIMEOUT: 30
      ports:
          - "5000:5000"
      volumes:
          - .:/code
      depends_on:
          - dynamodb

    dynamodb:
      container_name: local_dynamodb_profile_matcher
      image: amazon/dynamodb-local:1.15.0
      command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
      volumes:
        - ./dynamodb_data:/home/dynamodblocal/data
      ports:
        - "8000:8000"
    
    dynamodb_admin:
      container_name: local_dynamodb_admin_profile_matcher
      image: aaronshaf/dynamodb-admin:4.3.1
      environment:
        DYNAMO_ENDPOINT: "dynamodb:8000"  
      ports:
        - "8001:8001"
      depends_on:
        - dynamodb
      